(cl:in-package chassis_drive-msg)
(cl:export '(ALARM_FORKPHOTOE_LEFT_-VAL
          ALARM_FORKPHOTOE_LEFT_
          ALARM_FORKPHOTOE_RIGHT_-VAL
          ALARM_FORKPHOTOE_RIGHT_
          ALARM_CARGOPHOTOS_LEFT_-VAL
          ALARM_CARGOPHOTOS_LEFT_
          ALARM_CARGOPHOTOS_RIGHT_-VAL
          ALARM_CARGOPHOTOS_RIGHT_
          ALARM_MICRO_SWTICH_-VAL
          ALARM_MICRO_SWTICH_
          ALARM_COLLISION_AVOIDANCE_-VAL
          ALARM_COLLISION_AVOIDANCE_
          ALARM_EMERGENCY_STOP_SWTICH_-VAL
          ALARM_EMERGENCY_STOP_SWTICH_
          ALARM_AUTO_MAN_SWTICH_-VAL
          ALARM_AUTO_MAN_SWTICH_
          ALARM_UP_LIMIT_-VAL
          ALARM_UP_LIMIT_
          ALARM_DOWN_LIMIT_-VAL
          ALARM_DOWN_LIMIT_
))