(cl:in-package chassis_drive-msg)
(cl:export '(CHASSIS_MILEAGE_VARIABLE_-VAL
          CHASSIS_MILEAGE_VARIABLE_
          CHASSIS_MILEAGE_RECORD_-VAL
          CHASSIS_MILEAGE_RECORD_
          CHASSIS_DRIVE_SPEED_-VAL
          CHASSIS_DRIVE_SPEED_
          CHASSIS_DRIVE_ANGLE_-VAL
          CHASSIS_DRIVE_ANGLE_
          CHASSIS_DRIVEMOTOR_ERROR_CODE_-VAL
          CHASSIS_DRIVEMOTOR_ERROR_CODE_
          CHASSIS_WHIRLMOTOR_ERRO_CODE_-VAL
          CHASSIS_WHIRLMOTOR_ERRO_CODE_
          CHASSIS_LIFTMOTOR_ERRO_CODE_-VAL
          CHASSIS_LIFTMOTOR_ERRO_CODE_
          CHASSIS_TASK_ID_-VAL
          CHASSIS_TASK_ID_
          CHASSIS_TASK_STATE_-VAL
          CHASSIS_TASK_STATE_
          CHASSIS_SELFCHECK_ERROR_CODE_-VAL
          CHASSIS_SELFCHECK_ERROR_CODE_
))