// Generated by gencpp from file chassis_drive/cmd_lift.msg
// DO NOT EDIT!


#ifndef CHASSIS_DRIVE_MESSAGE_CMD_LIFT_H
#define CHASSIS_DRIVE_MESSAGE_CMD_LIFT_H

#include <ros/service_traits.h>


#include <chassis_drive/cmd_liftRequest.h>
#include <chassis_drive/cmd_liftResponse.h>


namespace chassis_drive
{

struct cmd_lift
{

typedef cmd_liftRequest Request;
typedef cmd_liftResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_lift
} // namespace chassis_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chassis_drive::cmd_lift > {
  static const char* value()
  {
    return "3ebadb64f1f7323f82c99c510cfe6f5c";
  }

  static const char* value(const ::chassis_drive::cmd_lift&) { return value(); }
};

template<>
struct DataType< ::chassis_drive::cmd_lift > {
  static const char* value()
  {
    return "chassis_drive/cmd_lift";
  }

  static const char* value(const ::chassis_drive::cmd_lift&) { return value(); }
};


// service_traits::MD5Sum< ::chassis_drive::cmd_liftRequest> should match
// service_traits::MD5Sum< ::chassis_drive::cmd_lift >
template<>
struct MD5Sum< ::chassis_drive::cmd_liftRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chassis_drive::cmd_lift >::value();
  }
  static const char* value(const ::chassis_drive::cmd_liftRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chassis_drive::cmd_liftRequest> should match
// service_traits::DataType< ::chassis_drive::cmd_lift >
template<>
struct DataType< ::chassis_drive::cmd_liftRequest>
{
  static const char* value()
  {
    return DataType< ::chassis_drive::cmd_lift >::value();
  }
  static const char* value(const ::chassis_drive::cmd_liftRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chassis_drive::cmd_liftResponse> should match
// service_traits::MD5Sum< ::chassis_drive::cmd_lift >
template<>
struct MD5Sum< ::chassis_drive::cmd_liftResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chassis_drive::cmd_lift >::value();
  }
  static const char* value(const ::chassis_drive::cmd_liftResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chassis_drive::cmd_liftResponse> should match
// service_traits::DataType< ::chassis_drive::cmd_lift >
template<>
struct DataType< ::chassis_drive::cmd_liftResponse>
{
  static const char* value()
  {
    return DataType< ::chassis_drive::cmd_lift >::value();
  }
  static const char* value(const ::chassis_drive::cmd_liftResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHASSIS_DRIVE_MESSAGE_CMD_LIFT_H
