(cl:defpackage agvs_control-srv
  (:use )
  (:export
   "CMD_CONTROL_MODE"
   "<CMD_CONTROL_MODE-REQUEST>"
   "CMD_CONTROL_MODE-REQUEST"
   "<CMD_CONTROL_MODE-RESPONSE>"
   "CMD_CONTROL_MODE-RESPONSE"
   "CMD_CONTROL_TASK"
   "<CMD_CONTROL_TASK-REQUEST>"
   "CMD_CONTROL_TASK-REQUEST"
   "<CMD_CONTROL_TASK-RESPONSE>"
   "CMD_CONTROL_TASK-RESPONSE"
  ))

