// Generated by gencpp from file agvs_control/cmd_control_mode.msg
// DO NOT EDIT!


#ifndef AGVS_CONTROL_MESSAGE_CMD_CONTROL_MODE_H
#define AGVS_CONTROL_MESSAGE_CMD_CONTROL_MODE_H

#include <ros/service_traits.h>


#include <agvs_control/cmd_control_modeRequest.h>
#include <agvs_control/cmd_control_modeResponse.h>


namespace agvs_control
{

struct cmd_control_mode
{

typedef cmd_control_modeRequest Request;
typedef cmd_control_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cmd_control_mode
} // namespace agvs_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agvs_control::cmd_control_mode > {
  static const char* value()
  {
    return "0545bf3db61acfe8473d040eb76fcb1c";
  }

  static const char* value(const ::agvs_control::cmd_control_mode&) { return value(); }
};

template<>
struct DataType< ::agvs_control::cmd_control_mode > {
  static const char* value()
  {
    return "agvs_control/cmd_control_mode";
  }

  static const char* value(const ::agvs_control::cmd_control_mode&) { return value(); }
};


// service_traits::MD5Sum< ::agvs_control::cmd_control_modeRequest> should match
// service_traits::MD5Sum< ::agvs_control::cmd_control_mode >
template<>
struct MD5Sum< ::agvs_control::cmd_control_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agvs_control::cmd_control_mode >::value();
  }
  static const char* value(const ::agvs_control::cmd_control_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvs_control::cmd_control_modeRequest> should match
// service_traits::DataType< ::agvs_control::cmd_control_mode >
template<>
struct DataType< ::agvs_control::cmd_control_modeRequest>
{
  static const char* value()
  {
    return DataType< ::agvs_control::cmd_control_mode >::value();
  }
  static const char* value(const ::agvs_control::cmd_control_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agvs_control::cmd_control_modeResponse> should match
// service_traits::MD5Sum< ::agvs_control::cmd_control_mode >
template<>
struct MD5Sum< ::agvs_control::cmd_control_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agvs_control::cmd_control_mode >::value();
  }
  static const char* value(const ::agvs_control::cmd_control_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvs_control::cmd_control_modeResponse> should match
// service_traits::DataType< ::agvs_control::cmd_control_mode >
template<>
struct DataType< ::agvs_control::cmd_control_modeResponse>
{
  static const char* value()
  {
    return DataType< ::agvs_control::cmd_control_mode >::value();
  }
  static const char* value(const ::agvs_control::cmd_control_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGVS_CONTROL_MESSAGE_CMD_CONTROL_MODE_H
