// Generated by gencpp from file agvs_control/cmd_control_taskResponse.msg
// DO NOT EDIT!


#ifndef AGVS_CONTROL_MESSAGE_CMD_CONTROL_TASKRESPONSE_H
#define AGVS_CONTROL_MESSAGE_CMD_CONTROL_TASKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agvs_control
{
template <class ContainerAllocator>
struct cmd_control_taskResponse_
{
  typedef cmd_control_taskResponse_<ContainerAllocator> Type;

  cmd_control_taskResponse_()
    {
    }
  cmd_control_taskResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_control_taskResponse_

typedef ::agvs_control::cmd_control_taskResponse_<std::allocator<void> > cmd_control_taskResponse;

typedef boost::shared_ptr< ::agvs_control::cmd_control_taskResponse > cmd_control_taskResponsePtr;
typedef boost::shared_ptr< ::agvs_control::cmd_control_taskResponse const> cmd_control_taskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace agvs_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::agvs_control::cmd_control_taskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agvs_control/cmd_control_taskResponse";
  }

  static const char* value(const ::agvs_control::cmd_control_taskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::agvs_control::cmd_control_taskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_control_taskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agvs_control::cmd_control_taskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::agvs_control::cmd_control_taskResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AGVS_CONTROL_MESSAGE_CMD_CONTROL_TASKRESPONSE_H
